export const MENTOR_LOGIN_REQUEST = 'MENTOR_LOGIN_REQUEST';
export const MENTOR_LOGIN_SUCCESS = 'MENTOR_LOGIN_SUCCESS';
export const MENTOR_LOGIN_FAIL = 'MENTOR_LOGIN_FAIL';
export const MENTOR_LOGOUT = 'MENTOR_LOGOUT';

export const MENTOR_REGISTER_REQUEST = 'MENTOR_REGISTER_REQUEST';
export const MENTOR_REGISTER_SUCCESS = 'MENTOR_REGISTER_SUCCESS';
export const MENTOR_REGISTER_FAIL = 'MENTOR_REGISTER_FAIL';

export const GET_LIST_REQUEST = 'GET_LIST_REQUEST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAIL = 'GET_LIST_FAIL';

export const ADD_MENTOR_REQUEST = 'ADD_MENTOR_REQUEST';
export const ADD_MENTOR_SUCCESS = 'ADD_MENTOR_SUCCESS';
export const ADD_MENTOR_FAIL = 'ADD_MENTOR_FAIL';
